import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="flex flex-row justify-between px-5 py-2">
          <Link href="/">Handicraft Sri Lanka</Link>
          <div className="flex flex-row gap-2">
            <Link href="/users">Users</Link>
            <Link href="/login">Login</Link>
            <Link href="/register">Register</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
