import "./globals.css";
import InjectionProvider from "@/injection/Injection";
import AuthStatusProvider from "@/logic/authStatusLogic/AuthStatusContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <InjectionProvider>
          <AuthStatusProvider>{children}</AuthStatusProvider>
        </InjectionProvider>
      </body>
    </html>
  );
}
